### ISSUE TITLE
Cannot properly render the debugger for my php script

### ISSUE THREAD

**Issue by arnissolle** [spatie/ignition#14]
Just followed the minimal example... did I miss something?
Of course, I've installed the package like so: `composer require spatie/ignition`

```php
<?php // ./app/index.php

namespace App;

use Spatie\Ignition\Ignition;

require __DIR__ . '/../vendor/autoload.php';

Ignition::make()->register();

throw new Exception('Bye world');
```

My directory structure:
```
.
├── app
│   └── index.php
├── bin
│   └── composer
├── composer.json
├── composer.lock
├── docker-compose.yml
└── vendor
    ├── autoload.php
    ├── bin
    ├── composer
    ├── doctrine
    └── ...
```

And my docker-compose.yml:
```
version: '3'
services:
  app:
    image: php:8.1-apache
    ports:
      - 89:80
    volumes:
      - .:/var/www/html
```

<img width="1792" alt="Capture d’écran 2021-12-16 à 19 33 28" src="https://user-images.githubusercontent.com/5046159/146428967-e1c5abf2-7cde-4add-9fd4-ed5bd239e1f2.png">
